# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Lr1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(985, 803)
        MainWindow.setStyleSheet("background-color:rgb(23, 25, 45);\n"
"color: rgb(250, 247, 253);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.language_choice = QtWidgets.QHBoxLayout()
        self.language_choice.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.language_choice.setContentsMargins(-1, 0, -1, 0)
        self.language_choice.setObjectName("language_choice")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.language_choice.addItem(spacerItem)
        self.Ru_btn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Ru_btn.setFont(font)
        self.Ru_btn.setStyleSheet("QPushButton {\n"
"  background-color:rgb(41, 41, 71);\n"
"  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"  border-radius: 8px;\n"
"  padding: 5px 15px;\n"
"  margin-top: 10px;\n"
"  outline: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(54, 53, 87);\n"
"}\n"
"")
        self.Ru_btn.setObjectName("Ru_btn")
        self.language_choice.addWidget(self.Ru_btn)
        self.English_btn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.English_btn.setFont(font)
        self.English_btn.setStyleSheet("QPushButton {\n"
"  background-color:rgb(41, 41, 71);\n"
"  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"  border-radius: 8px;\n"
"  padding: 5px 15px;\n"
"  margin-top: 10px;\n"
"  outline: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(54, 53, 87);\n"
"}\n"
"")
        self.English_btn.setObjectName("English_btn")
        self.language_choice.addWidget(self.English_btn)
        self.alf_alf = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.alf_alf.setFont(font)
        self.alf_alf.setStyleSheet("QPushButton {\n"
"  background-color:rgb(41, 41, 71);\n"
"  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"  border-radius: 8px;\n"
"  padding: 5px 15px;\n"
"  margin-top: 10px;\n"
"  outline: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(54, 53, 87);\n"
"}\n"
"")
        self.alf_alf.setObjectName("alf_alf")
        self.language_choice.addWidget(self.alf_alf)
        self.new_alf = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.new_alf.setFont(font)
        self.new_alf.setStyleSheet("QPushButton {\n"
"  background-color:rgb(41, 41, 71);\n"
"  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"  border-radius: 8px;\n"
"  padding: 5px 15px;\n"
"  margin-top: 10px;\n"
"  outline: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(54, 53, 87);\n"
"}\n"
"")
        self.new_alf.setObjectName("new_alf")
        self.language_choice.addWidget(self.new_alf)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.language_choice.addItem(spacerItem1)
        self.language_choice.setStretch(0, 10)
        self.language_choice.setStretch(1, 5)
        self.language_choice.setStretch(2, 5)
        self.language_choice.setStretch(5, 10)
        self.verticalLayout_3.addLayout(self.language_choice)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"\n"
"")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.character = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.character.setFont(font)
        self.character.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"\n"
"")
        self.character.setText("")
        self.character.setObjectName("character")
        self.horizontalLayout.addWidget(self.character)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.textfor = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.textfor.setFont(font)
        self.textfor.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;")
        self.textfor.setObjectName("textfor")
        self.verticalLayout.addWidget(self.textfor)
        self.reshenie = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.reshenie.setFont(font)
        self.reshenie.setStyleSheet("QPushButton {\n"
"  background-color:rgb(41, 41, 71);\n"
"  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"  border-radius: 8px;\n"
"  padding: 5px 15px;\n"
"  margin-top: 10px;\n"
"  outline: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(54, 53, 87);\n"
"}\n"
"")
        self.reshenie.setObjectName("reshenie")
        self.verticalLayout.addWidget(self.reshenie)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.findN = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.findN.setFont(font)
        self.findN.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"\n"
"")
        self.findN.setAlignment(QtCore.Qt.AlignCenter)
        self.findN.setObjectName("findN")
        self.horizontalLayout_2.addWidget(self.findN)
        self.findi = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.findi.setFont(font)
        self.findi.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"\n"
"")
        self.findi.setAlignment(QtCore.Qt.AlignCenter)
        self.findi.setObjectName("findi")
        self.horizontalLayout_2.addWidget(self.findi)
        self.findI = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.findI.setFont(font)
        self.findI.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"\n"
"")
        self.findI.setAlignment(QtCore.Qt.AlignCenter)
        self.findI.setObjectName("findI")
        self.horizontalLayout_2.addWidget(self.findI)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.fi_N = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.fi_N.setFont(font)
        self.fi_N.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"\n"
"")
        self.fi_N.setText("")
        self.fi_N.setAlignment(QtCore.Qt.AlignCenter)
        self.fi_N.setObjectName("fi_N")
        self.horizontalLayout_5.addWidget(self.fi_N)
        self.fi_i = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.fi_i.setFont(font)
        self.fi_i.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"\n"
"")
        self.fi_i.setText("")
        self.fi_i.setAlignment(QtCore.Qt.AlignCenter)
        self.fi_i.setObjectName("fi_i")
        self.horizontalLayout_5.addWidget(self.fi_i)
        self.fi_I = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.fi_I.setFont(font)
        self.fi_I.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"\n"
"")
        self.fi_I.setText("")
        self.fi_I.setAlignment(QtCore.Qt.AlignCenter)
        self.fi_I.setObjectName("fi_I")
        self.horizontalLayout_5.addWidget(self.fi_I)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.setStretch(0, 20)
        self.verticalLayout_3.setStretch(1, 20)
        self.verticalLayout_3.setStretch(2, 500)
        self.verticalLayout_3.setStretch(3, 100)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.pokasform = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pokasform.setFont(font)
        self.pokasform.setStyleSheet("QPushButton {\n"
"  background-color:rgb(41, 41, 71);\n"
"  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"  border-radius: 8px;\n"
"  padding: 5px 15px;\n"
"  margin-top: 10px;\n"
"  outline: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(54, 53, 87);\n"
"}  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"\n"
"")
        self.pokasform.setObjectName("pokasform")
        self.verticalLayout_4.addWidget(self.pokasform)
        self.open_win = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.open_win.setFont(font)
        self.open_win.setStyleSheet("QPushButton {\n"
"  background-color:rgb(41, 41, 71);\n"
"  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"  border-radius: 8px;\n"
"  padding: 5px 15px;\n"
"  margin-top: 10px;\n"
"  outline: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(54, 53, 87);\n"
"}\n"
"")
        self.open_win.setObjectName("open_win")
        self.verticalLayout_4.addWidget(self.open_win)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.Ru_btn, self.English_btn)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Ru_btn.setText(_translate("MainWindow", "Русский"))
        self.English_btn.setText(_translate("MainWindow", "Английский "))
        self.alf_alf.setText(_translate("MainWindow", "Свой алфавит"))
        self.new_alf.setText(_translate("MainWindow", "Редактировать алфавит"))
        self.label.setText(_translate("MainWindow", "Количество букв в языке:"))
        self.reshenie.setText(_translate("MainWindow", "Вычислить"))
        self.findN.setText(_translate("MainWindow", "N = "))
        self.findi.setText(_translate("MainWindow", "i ="))
        self.findI.setText(_translate("MainWindow", "I = "))
        self.pokasform.setText(_translate("MainWindow", "Показать решение"))
        self.open_win.setText(_translate("MainWindow", "Задачи"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
