# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ru.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ru_lang(object):
    def setupUi(self, Ru_lang):
        Ru_lang.setObjectName("Ru_lang")
        Ru_lang.resize(1432, 872)
        Ru_lang.setStyleSheet("background-color:rgb(23, 25, 45);\n"
"color: rgb(250, 247, 253);")
        self.centralwidget = QtWidgets.QWidget(Ru_lang)
        self.centralwidget.setStyleSheet("QPushButton {\n"
"  background-color:rgb(41, 41, 71);\n"
"  color: rgb(252, 248, 255);\n"
"  font-weight: 1000;\n"
"  font: bold 40px;\n"
"  border-radius: 8px;\n"
"  padding: 5px 15px;\n"
"  margin-top: 10px;\n"
"  outline: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(54, 53, 87);\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_11.addWidget(self.label_21)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_11.addWidget(self.label)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_11.addWidget(self.pushButton_2)
        self.no1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.no1.setFont(font)
        self.no1.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"\n"
"")
        self.no1.setText("")
        self.no1.setAlignment(QtCore.Qt.AlignCenter)
        self.no1.setObjectName("no1")
        self.horizontalLayout_11.addWidget(self.no1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_10.addWidget(self.label_22)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_10.addWidget(self.label_3)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_10.addWidget(self.pushButton_3)
        self.no2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.no2.setFont(font)
        self.no2.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"\n"
"")
        self.no2.setText("")
        self.no2.setAlignment(QtCore.Qt.AlignCenter)
        self.no2.setObjectName("no2")
        self.horizontalLayout_10.addWidget(self.no2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_9.addWidget(self.label_23)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"\n"
"")
        self.label_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_9.addWidget(self.pushButton_8)
        self.no3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.no3.setFont(font)
        self.no3.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"\n"
"")
        self.no3.setText("")
        self.no3.setAlignment(QtCore.Qt.AlignCenter)
        self.no3.setObjectName("no3")
        self.horizontalLayout_9.addWidget(self.no3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"")
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_8.addWidget(self.label_24)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"\n"
"")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_8.addWidget(self.pushButton_10)
        self.no4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.no4.setFont(font)
        self.no4.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"\n"
"")
        self.no4.setText("")
        self.no4.setAlignment(QtCore.Qt.AlignCenter)
        self.no4.setObjectName("no4")
        self.horizontalLayout_8.addWidget(self.no4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_7.addWidget(self.label_25)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"\n"
"")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_7.addWidget(self.pushButton_4)
        self.no5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.no5.setFont(font)
        self.no5.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"\n"
"")
        self.no5.setText("")
        self.no5.setAlignment(QtCore.Qt.AlignCenter)
        self.no5.setObjectName("no5")
        self.horizontalLayout_7.addWidget(self.no5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"")
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_6.addWidget(self.label_26)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"\n"
"")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_6.addWidget(self.pushButton_5)
        self.no6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.no6.setFont(font)
        self.no6.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"\n"
"")
        self.no6.setText("")
        self.no6.setAlignment(QtCore.Qt.AlignCenter)
        self.no6.setObjectName("no6")
        self.horizontalLayout_6.addWidget(self.no6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"")
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_5.addWidget(self.label_27)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"\n"
"")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_5.addWidget(self.pushButton_6)
        self.no7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.no7.setFont(font)
        self.no7.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"\n"
"")
        self.no7.setText("")
        self.no7.setAlignment(QtCore.Qt.AlignCenter)
        self.no7.setObjectName("no7")
        self.horizontalLayout_5.addWidget(self.no7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"")
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_4.addWidget(self.label_28)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"\n"
"")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_4.addWidget(self.label_16)
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_4.addWidget(self.pushButton_7)
        self.no8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.no8.setFont(font)
        self.no8.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"\n"
"")
        self.no8.setText("")
        self.no8.setAlignment(QtCore.Qt.AlignCenter)
        self.no8.setObjectName("no8")
        self.horizontalLayout_4.addWidget(self.no8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem7)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"")
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_3.addWidget(self.label_29)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"\n"
"")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_3.addWidget(self.label_17)
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_3.addWidget(self.pushButton_9)
        self.no9 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.no9.setFont(font)
        self.no9.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"\n"
"")
        self.no9.setText("")
        self.no9.setAlignment(QtCore.Qt.AlignCenter)
        self.no9.setObjectName("no9")
        self.horizontalLayout_3.addWidget(self.no9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem8)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"")
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout.addWidget(self.label_30)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"\n"
"")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout.addWidget(self.label_18)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.no10 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.no10.setFont(font)
        self.no10.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"\n"
"")
        self.no10.setText("")
        self.no10.setAlignment(QtCore.Qt.AlignCenter)
        self.no10.setObjectName("no10")
        self.horizontalLayout.addWidget(self.no10)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        Ru_lang.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Ru_lang)
        self.statusbar.setObjectName("statusbar")
        Ru_lang.setStatusBar(self.statusbar)

        self.retranslateUi(Ru_lang)
        QtCore.QMetaObject.connectSlotsByName(Ru_lang)

    def retranslateUi(self, Ru_lang):
        _translate = QtCore.QCoreApplication.translate
        Ru_lang.setWindowTitle(_translate("Ru_lang", "MainWindow"))
        self.label_21.setText(_translate("Ru_lang", "1"))
        self.label.setText(_translate("Ru_lang", "<html><head/><body><p>Дано:<br/>N = 2^7<br/>k = 70</p></body></html>"))
        self.pushButton_2.setText(_translate("Ru_lang", "Ответ"))
        self.label_22.setText(_translate("Ru_lang", "2"))
        self.label_3.setText(_translate("Ru_lang", "<html><head/><body><p>k = 60</p><p>N = 125</p><p>i = 7</p></body></html>"))
        self.pushButton_3.setText(_translate("Ru_lang", "Ответ"))
        self.label_23.setText(_translate("Ru_lang", "3"))
        self.label_5.setText(_translate("Ru_lang", "<html><head/><body><p>N = 2^4</p><p>k = 150</p></body></html>"))
        self.pushButton_8.setText(_translate("Ru_lang", "Ответ"))
        self.label_24.setText(_translate("Ru_lang", "4"))
        self.label_7.setText(_translate("Ru_lang", "<html><head/><body><p>k = 80</p><p>N = 2^7</p></body></html>"))
        self.pushButton_10.setText(_translate("Ru_lang", "Ответ"))
        self.label_25.setText(_translate("Ru_lang", "5"))
        self.label_9.setText(_translate("Ru_lang", "<html><head/><body><p>N = 2^2</p><p>k = 30*10</p></body></html>"))
        self.pushButton_4.setText(_translate("Ru_lang", "Ответ"))
        self.label_26.setText(_translate("Ru_lang", "6"))
        self.label_11.setText(_translate("Ru_lang", "<html><head/><body><p>N = 18</p></body></html>"))
        self.pushButton_5.setText(_translate("Ru_lang", "Ответ"))
        self.label_27.setText(_translate("Ru_lang", "7"))
        self.label_13.setText(_translate("Ru_lang", "N = 2^i"))
        self.pushButton_6.setText(_translate("Ru_lang", "Ответ"))
        self.label_28.setText(_translate("Ru_lang", "8"))
        self.label_16.setText(_translate("Ru_lang", "N = 3^i"))
        self.pushButton_7.setText(_translate("Ru_lang", "Ответ"))
        self.label_29.setText(_translate("Ru_lang", "9"))
        self.label_17.setText(_translate("Ru_lang", "<html><head/><body><p>k = 300<br/>N = n^5</p></body></html>"))
        self.pushButton_9.setText(_translate("Ru_lang", "Ответ"))
        self.label_30.setText(_translate("Ru_lang", "10"))
        self.label_18.setText(_translate("Ru_lang", "k = 1000"))
        self.pushButton.setText(_translate("Ru_lang", "Ответ"))
