# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'two_windows.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_alf_two(object):
    def setupUi(self, alf_two):
        alf_two.setObjectName("alf_two")
        alf_two.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(alf_two)
        self.centralwidget.setStyleSheet("background-color:rgb(23, 25, 45);\n"
"  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.textforalf = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.textforalf.setFont(font)
        self.textforalf.setStyleSheet("  color: rgb(252, 248, 255);\n"
"  font-weight: 600;")
        self.textforalf.setObjectName("textforalf")
        self.verticalLayout.addWidget(self.textforalf)
        self.clean_btn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.clean_btn.setFont(font)
        self.clean_btn.setStyleSheet("QPushButton {\n"
"  background-color:rgb(41, 41, 71);\n"
"  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"  border-radius: 8px;\n"
"  padding: 5px 15px;\n"
"  margin-top: 10px;\n"
"  outline: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(54, 53, 87);\n"
"}\n"
"")
        self.clean_btn.setObjectName("clean_btn")
        self.verticalLayout.addWidget(self.clean_btn)
        self.add_btn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.add_btn.setFont(font)
        self.add_btn.setStyleSheet("QPushButton {\n"
"  background-color:rgb(41, 41, 71);\n"
"  color: rgb(252, 248, 255);\n"
"  font-weight: 600;\n"
"  border-radius: 8px;\n"
"  padding: 5px 15px;\n"
"  margin-top: 10px;\n"
"  outline: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(54, 53, 87);\n"
"}\n"
"")
        self.add_btn.setObjectName("add_btn")
        self.verticalLayout.addWidget(self.add_btn)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        alf_two.setCentralWidget(self.centralwidget)

        self.retranslateUi(alf_two)
        QtCore.QMetaObject.connectSlotsByName(alf_two)

    def retranslateUi(self, alf_two):
        _translate = QtCore.QCoreApplication.translate
        alf_two.setWindowTitle(_translate("alf_two", "MainWindow"))
        self.label.setText(_translate("alf_two", "Свой алфавит"))
        self.label_2.setText(_translate("alf_two", "!Каждый новый символ алфавита должен отделен пробелом!"))
        self.clean_btn.setText(_translate("alf_two", "Очистить"))
        self.add_btn.setText(_translate("alf_two", "Изменить алфавит"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    alf_two = QtWidgets.QMainWindow()
    ui = Ui_alf_two()
    ui.setupUi(alf_two)
    alf_two.show()
    sys.exit(app.exec_())
